name: Hello GIthub Actions #ワークフローの名前を指定

on:   #トリガーとなるイベントを定義
  push:
    branches:
      - main

  pull_request:
    branches:
      - feature/**

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
      - run: echo "Github Actions!!"
  gha-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello,Github Actions."
